#This file written by /home/con/DNA_Methylation/Public_data/make_commands.pl
library(methylSig)
fileList = c("/home/con/DNA_Methylation/Public_data/R/BL01_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL02_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL03_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL04_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL05_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL06_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL07_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL08_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL09_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/BL10_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL01_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL02_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL03_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL04_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL05_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL06_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL07_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL08_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL09_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv","/home/con/DNA_Methylation/Public_data/R/FL10_artif.chr10.WGBS_background.1_DMR.class.1.bsmooth.tsv")
sample.id=c("B1\",\"B2\",\"B3\",\"B4\",\"B5\",\"B6\",\"B7\",\"B8\",\"B9\",\"B10\",\"F1\",\"F2\",\"F3\",\"F4\",\"F5\",\"F6\",\"F7\",\"F8\",\"F9\",\"F10")
treatment = c(0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1)
meth <- methylSigReadData(fileList, sample.ids = sample.id, assembly = 'mm9',treatment = treatment, context = "CpG", destranded=TRUE, minCount = 10)
methTile = methylSigTile(meth,win.size = 25)
myDiff = methylSigCalc(methTile, groups=c(1,0), min.per.group=3, local.disp =TRUE)
write.methylSigDiff(myDiff, file="1.1.methylSig.tile.answers.tsv", quote=FALSE, row.names=FALSE)
