/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 1.1.RRBS.metilene_input > 1.1.CpG1.RRBS.stdout 2> 1.1.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 1.1.RRBS.metilene_input > 1.1.CpG2.RRBS.stdout 2> 1.1.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 1.1.RRBS.metilene_input > 1.1.CpG3.RRBS.stdout 2> 1.1.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 1.1.RRBS.metilene_input > 1.1.CpG4.RRBS.stdout 2> 1.1.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 1.1.RRBS.metilene_input > 1.1.CpG5.RRBS.stdout 2> 1.1.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 1.1.RRBS.metilene_input > 1.1.CpG6.RRBS.stdout 2> 1.1.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 1.1.RRBS.metilene_input > 1.1.CpG7.RRBS.stdout 2> 1.1.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 1.1.RRBS.metilene_input > 1.1.CpG8.RRBS.stdout 2> 1.1.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 1.1.RRBS.metilene_input > 1.1.CpG9.RRBS.stdout 2> 1.1.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 1.1.RRBS.metilene_input > 1.1.CpG10.RRBS.stdout 2> 1.1.CpG10.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 1.2.RRBS.metilene_input > 1.2.CpG1.RRBS.stdout 2> 1.2.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 1.2.RRBS.metilene_input > 1.2.CpG2.RRBS.stdout 2> 1.2.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 1.2.RRBS.metilene_input > 1.2.CpG3.RRBS.stdout 2> 1.2.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 1.2.RRBS.metilene_input > 1.2.CpG4.RRBS.stdout 2> 1.2.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 1.2.RRBS.metilene_input > 1.2.CpG5.RRBS.stdout 2> 1.2.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 1.2.RRBS.metilene_input > 1.2.CpG6.RRBS.stdout 2> 1.2.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 1.2.RRBS.metilene_input > 1.2.CpG7.RRBS.stdout 2> 1.2.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 1.2.RRBS.metilene_input > 1.2.CpG8.RRBS.stdout 2> 1.2.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 1.2.RRBS.metilene_input > 1.2.CpG9.RRBS.stdout 2> 1.2.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 1.2.RRBS.metilene_input > 1.2.CpG10.RRBS.stdout 2> 1.2.CpG10.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 1.3.RRBS.metilene_input > 1.3.CpG1.RRBS.stdout 2> 1.3.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 1.3.RRBS.metilene_input > 1.3.CpG2.RRBS.stdout 2> 1.3.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 1.3.RRBS.metilene_input > 1.3.CpG3.RRBS.stdout 2> 1.3.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 1.3.RRBS.metilene_input > 1.3.CpG4.RRBS.stdout 2> 1.3.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 1.3.RRBS.metilene_input > 1.3.CpG5.RRBS.stdout 2> 1.3.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 1.3.RRBS.metilene_input > 1.3.CpG6.RRBS.stdout 2> 1.3.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 1.3.RRBS.metilene_input > 1.3.CpG7.RRBS.stdout 2> 1.3.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 1.3.RRBS.metilene_input > 1.3.CpG8.RRBS.stdout 2> 1.3.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 1.3.RRBS.metilene_input > 1.3.CpG9.RRBS.stdout 2> 1.3.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 1.3.RRBS.metilene_input > 1.3.CpG10.RRBS.stdout 2> 1.3.CpG10.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 1.4.RRBS.metilene_input > 1.4.CpG1.RRBS.stdout 2> 1.4.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 1.4.RRBS.metilene_input > 1.4.CpG2.RRBS.stdout 2> 1.4.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 1.4.RRBS.metilene_input > 1.4.CpG3.RRBS.stdout 2> 1.4.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 1.4.RRBS.metilene_input > 1.4.CpG4.RRBS.stdout 2> 1.4.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 1.4.RRBS.metilene_input > 1.4.CpG5.RRBS.stdout 2> 1.4.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 1.4.RRBS.metilene_input > 1.4.CpG6.RRBS.stdout 2> 1.4.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 1.4.RRBS.metilene_input > 1.4.CpG7.RRBS.stdout 2> 1.4.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 1.4.RRBS.metilene_input > 1.4.CpG8.RRBS.stdout 2> 1.4.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 1.4.RRBS.metilene_input > 1.4.CpG9.RRBS.stdout 2> 1.4.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 1.4.RRBS.metilene_input > 1.4.CpG10.RRBS.stdout 2> 1.4.CpG10.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 2.1.RRBS.metilene_input > 2.1.CpG1.RRBS.stdout 2> 2.1.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 2.1.RRBS.metilene_input > 2.1.CpG2.RRBS.stdout 2> 2.1.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 2.1.RRBS.metilene_input > 2.1.CpG3.RRBS.stdout 2> 2.1.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 2.1.RRBS.metilene_input > 2.1.CpG4.RRBS.stdout 2> 2.1.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 2.1.RRBS.metilene_input > 2.1.CpG5.RRBS.stdout 2> 2.1.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 2.1.RRBS.metilene_input > 2.1.CpG6.RRBS.stdout 2> 2.1.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 2.1.RRBS.metilene_input > 2.1.CpG7.RRBS.stdout 2> 2.1.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 2.1.RRBS.metilene_input > 2.1.CpG8.RRBS.stdout 2> 2.1.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 2.1.RRBS.metilene_input > 2.1.CpG9.RRBS.stdout 2> 2.1.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 2.1.RRBS.metilene_input > 2.1.CpG10.RRBS.stdout 2> 2.1.CpG10.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 2.2.RRBS.metilene_input > 2.2.CpG1.RRBS.stdout 2> 2.2.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 2.2.RRBS.metilene_input > 2.2.CpG2.RRBS.stdout 2> 2.2.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 2.2.RRBS.metilene_input > 2.2.CpG3.RRBS.stdout 2> 2.2.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 2.2.RRBS.metilene_input > 2.2.CpG4.RRBS.stdout 2> 2.2.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 2.2.RRBS.metilene_input > 2.2.CpG5.RRBS.stdout 2> 2.2.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 2.2.RRBS.metilene_input > 2.2.CpG6.RRBS.stdout 2> 2.2.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 2.2.RRBS.metilene_input > 2.2.CpG7.RRBS.stdout 2> 2.2.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 2.2.RRBS.metilene_input > 2.2.CpG8.RRBS.stdout 2> 2.2.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 2.2.RRBS.metilene_input > 2.2.CpG9.RRBS.stdout 2> 2.2.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 2.2.RRBS.metilene_input > 2.2.CpG10.RRBS.stdout 2> 2.2.CpG10.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 2.3.RRBS.metilene_input > 2.3.CpG1.RRBS.stdout 2> 2.3.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 2.3.RRBS.metilene_input > 2.3.CpG2.RRBS.stdout 2> 2.3.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 2.3.RRBS.metilene_input > 2.3.CpG3.RRBS.stdout 2> 2.3.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 2.3.RRBS.metilene_input > 2.3.CpG4.RRBS.stdout 2> 2.3.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 2.3.RRBS.metilene_input > 2.3.CpG5.RRBS.stdout 2> 2.3.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 2.3.RRBS.metilene_input > 2.3.CpG6.RRBS.stdout 2> 2.3.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 2.3.RRBS.metilene_input > 2.3.CpG7.RRBS.stdout 2> 2.3.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 2.3.RRBS.metilene_input > 2.3.CpG8.RRBS.stdout 2> 2.3.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 2.3.RRBS.metilene_input > 2.3.CpG9.RRBS.stdout 2> 2.3.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 2.3.RRBS.metilene_input > 2.3.CpG10.RRBS.stdout 2> 2.3.CpG10.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 1 2.4.RRBS.metilene_input > 2.4.CpG1.RRBS.stdout 2> 2.4.CpG1.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 2 2.4.RRBS.metilene_input > 2.4.CpG2.RRBS.stdout 2> 2.4.CpG2.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 3 2.4.RRBS.metilene_input > 2.4.CpG3.RRBS.stdout 2> 2.4.CpG3.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 4 2.4.RRBS.metilene_input > 2.4.CpG4.RRBS.stdout 2> 2.4.CpG4.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 5 2.4.RRBS.metilene_input > 2.4.CpG5.RRBS.stdout 2> 2.4.CpG5.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 6 2.4.RRBS.metilene_input > 2.4.CpG6.RRBS.stdout 2> 2.4.CpG6.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 7 2.4.RRBS.metilene_input > 2.4.CpG7.RRBS.stdout 2> 2.4.CpG7.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 8 2.4.RRBS.metilene_input > 2.4.CpG8.RRBS.stdout 2> 2.4.CpG8.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 9 2.4.RRBS.metilene_input > 2.4.CpG9.RRBS.stdout 2> 2.4.CpG9.RRBS.time
/usr/bin/time /home/con/DNA_Methylation/Public_data/metilene_v0.2-6/metilene_linux64 -m 10 2.4.RRBS.metilene_input > 2.4.CpG10.RRBS.stdout 2> 2.4.CpG10.RRBS.time
